apiVersion: v1
description: A Helm chart for Nest.js applications on Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: nest-app
version: 

keywords:
- nodejs
- nestjs
- node

maintainers:
- name: eCompliance Inc
  email: devops@ecompliance.com

sources:
- https://www.ecompliance.com
- https://github.com/Field-ID