# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# Auto Scaler
minReplicas: 1
maxReplicas: 4
targetAverageCpuUtilization: 99

image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:
  # TYPEORM_HOST:
  # TYPEORM_USERNAME:
  # TYPEORM_PASSWORD:
  # TYPEORM_DATABASE:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: nest-app
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

##
## PostgreSQL chart configuration
##

##
postgresql:
  ## Whether to deploy a PostgreSQL server to satisfy the applications database requirements. 
  ## To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable PostgreSQL replication
  replication:
    enabled: false
  ## PostgreSQL admin user
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
  postgresqlUsername: wildfire
  postgresqlPassword: wildfire
  postgresqlDatabase: wildfire

externaldb:
  username: wildfire
  password: wildfire
  database: wildfire